export const categories = ["science", "tech", "politics", "philosophy", "business"];

export const posts = [
  {
    id: 1,
    slug: "edge-pipelines",
    title: "Edge pipelines without the drama",
    summary: "Lightweight playbook for deploying tiny services to noisy edges.",
    category: "tech",
    tags: ["edge", "streaming", "ops"],
    date: "2024-12-02",
    markdown: "/assets/posts/edge-pipelines.md",
  },
  {
    id: 2,
    slug: "quantum-systems",
    title: "Quantum systems that feel like code",
    summary: "Notes on wiring lab-grade measurements with programmer-minded tooling.",
    category: "science",
    tags: ["quantum", "experiments", "signal"],
    date: "2024-09-19",
    markdown: "/assets/posts/quantum-systems.md",
  },
  {
    id: 3,
    slug: "digital-commons",
    title: "Digital commons and the civic stack",
    summary: "A civic-ops perspective on governing shared digital infrastructure.",
    category: "politics",
    tags: ["policy", "internet", "civic-tech"],
    date: "2024-07-14",
    markdown: "/assets/posts/digital-commons.md",
  },
  {
    id: 4,
    slug: "ethics-automation",
    title: "Automation with a conscience",
    summary: "Notes on building agents that respect human boundaries.",
    category: "philosophy",
    tags: ["ethics", "automation", "design"],
    date: "2024-10-05",
    markdown: "/assets/posts/ethics-automation.md",
  },
  {
    id: 5,
    slug: "ops-capital",
    title: "Operational capital for builders",
    summary: "A minimalist toolkit for measuring and extending execution runway.",
    category: "business",
    tags: ["ops", "runway", "cadence"],
    date: "2024-11-18",
    markdown: "/assets/posts/ops-capital.md",
  },
];
